### ISSUE TITLE
Add support to set the Host header sent to the service behind the proxy using environment variables

### ISSUE THREAD

**Issue by mauricios** [fsouza/docker-ssl-proxy#11]
In some cases is it necessary to forward the same requested host to the service behind the proxy, this can be done sending the requested Host using the `proxy_set_header` directive, like this:

`proxy_set_header   Host       $host;`

I think this can be done creating a new environment variable `TARGET_HOST_HEADER`, just to set this behavior as the default since this SSL is intended to be as transparent as possible.

**Comment by fsouza** [comment]
Hi @mauricios thanks for reporting this, just pushed a change that adds support for that environment variable.

**Comment by mauricios** [comment]
Thanks @fsouza For those who are interesting in configuring the default behavior for a transparent proxy just set the `TARGET_HOST_HEADER` to `"$$host"` in the `docker-composer` file.
