### ISSUE TITLE
Generate a CA certificate that can be shared between containers

### ISSUE THREAD

**Issue by dw-ec** [fsouza/docker-ssl-proxy#121]
Prior to pull request #20, this image would generate a CA certificate and use that to sign the server certificate. This CA cert could be shared between multiple ``docker-ssl-proxy``s making it easier for containers in the cluster to trust each other. 

The single CA certificate could also conceivably be installed onto developers' workstations, avoiding the need to explicitly override browser security warnings for every service visited.

This feature was removed due to issue #19, I think perhaps unnecessarily. The current README still asserts that the CA cert can be found in /etc/nginx/ca, but that directory no longer gets created and there is no CA cert to be found.

**Comment by fsouza** [comment]
Thanks for fixing this!
