### ISSUE TITLE
Support new MacOS 10.15 and iOS 13 certificates

### ISSUE THREAD

**Issue by ianneub** [fsouza/docker-ssl-proxy#19]
I've got some developers who recently updated to MacOS 10.15. After the upgrade they were unable to access their dev env that was being proxied by this docker container image. They would get an error indicating that the SSL cert was not trusted and did not get an option to ignore the warning.

Apparently Apple now requires some specific features of the SSL cert to be present before they will let you ignore the self-signed/untrusted CA cert.

https://support.apple.com/en-us/HT210176

Looking at the `add_self_signed_certs.sh` it seems that the code is using several steps to create the cert. I'm not sure if this is required or not for a specific use case, but I was able to get my clients working with the following code.

```
openssl req -x509 -nodes -newkey rsa:2048 -keyout key.pem -out cert.pem -days 825 -config config.cnf -extensions v3_req -subj "/C=US/ST=California/L=Los Angeles/O=Development/CN=My Dev Cert"
```

config.cnf looks like this:
```
[req]
distinguished_name = req_distinguished_name

[req_distinguished_name]
countryName = Country Name (2 letter code)
countryName_default = US
localityName = Locality Name (eg, city)
organizationalUnitName = Organizational Unit Name (eg, section)
commonName = Common Name (eg, YOUR name)
commonName_default = My Dev Cert
commonName_max = 64

[v3_req] 
keyUsage = keyEncipherment, dataEncipherment
extendedKeyUsage = serverAuth
subjectAltName = @alt_names

[alt_names]
DNS.1   = ${DOMAIN}
```

I can make the changes and create a PR if this looks like something you'd want to merge in.

**Comment by fsouza** [comment]
Hey @ianneub, thanks for opening this issue. The change makes sense, I'd be happy to accept a PR! :D
