### ISSUE TITLE
container restart needed when new cert is published

### ISSUE THREAD

**Issue by yourizwart** [fsouza/docker-ssl-proxy#49]
We are using Certbot to generate our new certificates.
Certbot publishes the certs to a volume which is in turn linked to the key and cert file in the ssl-proxy container.

The problem we facing is that every time certbot renews the certs this is not picked up by the container but a manual restart is needed to get things back in action.

**Comment by fsouza** [comment]
You probably need to configure to reload nginx after the cert is generated. You can do that by invoking `/usr/sbin/nginx -s reload`. iirc, certbot has hooks that you can use to invoke that command automatically, but I don't know the details 🙈

**Comment by yourizwart** [comment]
Ah ok, sorry I wasn't aware this was a certbot specific problem, sorry for opening this ticket then :).

**Comment by fsouza** [comment]
@yourizwart no worries, I don't think it's a certbot issue, it's a cergbot + nginx combination. Feel free to open issues in the feature if you encounter other issues!
