### ISSUE TITLE
ERR_SSL_KEY_USAGE_INCOMPATIBLE error when using latest image

### ISSUE THREAD

**Issue by maxsatula** [fsouza/docker-ssl-proxy#56]
Have **ERR_SSL_KEY_USAGE_INCOMPATIBLE** error in a browser (tried Chrome and new Microsoft Edge) when using latest image of docker-ssl-proxy, digest `e53808a30819`

However, everything works fine (except security warning which is expected) for tag **1.1** `fsouza/docker-ssl-proxy:1.1` digest `af2ba354f0d1`

**Comment by fsouza** [comment]
@maxsatula can you try the latest tag and see if that fixes it?

**Comment by maxsatula** [comment]
@fsouza Much better, thanks! Closing
