### ISSUE TITLE
Redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by MisterX2000** [fsouza/docker-ssl-proxy#64]
It would be nice, if the nginx server would automatically redirect HTTP requests to HTTPS.
This could be implemented directly in the nginx config and maybe additionally as an environment variable, if someone doesn't want this behavior.

**Comment by fsouza** [comment]
I think we can force the redirect and add an option only if someone requests it. Always redirecting makes sense as the default behavior.

**Comment by fsouza** [comment]
Actually, I'll hold off on this. We're not currently listening for unencrypted HTTP requests.

@MisterX2000 can you add more information about your use-case? Is it for testing purposes? I imagine that in a testing environment the protocol redirect isn't that important, but let me know if I'm missing something.

**Comment by MisterX2000** [comment]
I've just noticed it, when I tried to access my container from a Browser, that it didn't redirect me to HTTPS and just showed an `400 Bad Request: The plain HTTP request was sent to HTTPS port` Error.
So I thought it would be better to redirect it automatically if the Browser doesn't do so by itself.

**Comment by fsouza** [comment]
Oh I see, I thought you meant actually support HTTP, but if we only want to force HTTPS, that's doable. Will push a change.
