### ISSUE TITLE
Feature request: Please maintain version tags in Docker Hub

### ISSUE THREAD

**Issue by andrewodri** [fsouza/docker-ssl-proxy#8]
This is more of a best practice thing, but prevents users from losing previous images forever. I addition to pushing the most recent `latest` tag, perhaps pushing fresh semver or YYYYMMDD tagged images alongside it would allow users to pin to versions they know are compatible with their configuration.

And thanks for maintaining this; this image has been a quick & easy drop-in for testing proxy-pass directives locally before dropping them in front of production load balancers :)

**Comment by fsouza** [comment]
Hey @andrewodri, thanks for reporting this. I just set up the integration with Docker Hub and created the initial tag. It should be available soon! :)
